[package]
name = "polars-tools-derive"
version = "0.1.0"
edition = "2021"
description = "Derive macros for polars-tools"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }